In [1]:
import pandas as pd
import numpy as np
from sklearn import svm

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns; 

In [7]:
recipes=pd.read_csv('recipes_muffins_cupcakes.csv')
print(recipes)

       Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0    Muffin     55    28      3       7    5              2        0     0
1    Muffin     47    24     12       6    9              1        0     0
2    Muffin     47    23     18       6    4              1        0     0
3    Muffin     45    11     17      17    8              1        0     0
4    Muffin     50    25     12       6    5              2        1     0
5    Muffin     55    27      3       7    5              2        1     0
6    Muffin     54    27      7       5    5              2        0     0
7    Muffin     47    26     10      10    4              1        0     0
8    Muffin     50    17     17       8    6              1        0     0
9    Muffin     50    17     17      11    4              1        0     0
10  Cupcake     39     0     26      19   14              1        1     0
11  Cupcake     42    21     16      10    8              3        0     0
12  Cupcake     34    17 

In [4]:
x = recipes[['Sugar','Flour']].values
y = np.where(recipes['Type']=='Muffin',0,1)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [26]:
model1 = svm.SVC(kernel='rbf')
model1.fit(x_train, y_train)

SVC()

In [27]:
pred = model1.predict(x_test)
print(pred)

[0 0 0 1]


In [28]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
print(confusion_matrix(y_test,pred))

[[3 0]
 [0 1]]


In [29]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [30]:
print(accuracy_score(y_test,pred))

1.0
